# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import control_pb2 as control__pb2


class ControlStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.addMACsecProtectRule = channel.unary_unary(
        '/Control/addMACsecProtectRule',
        request_serializer=control__pb2.MACsecProtectRule.SerializeToString,
        response_deserializer=control__pb2.control_status.FromString,
        )
    self.addMACsecValidateRule = channel.unary_unary(
        '/Control/addMACsecValidateRule',
        request_serializer=control__pb2.MACsecValidateRule.SerializeToString,
        response_deserializer=control__pb2.control_status.FromString,
        )
    self.deleteMACsecProtectRule = channel.unary_unary(
        '/Control/deleteMACsecProtectRule',
        request_serializer=control__pb2.MACsecProtectRule.SerializeToString,
        response_deserializer=control__pb2.control_status.FromString,
        )
    self.deleteMACsecValidateRule = channel.unary_unary(
        '/Control/deleteMACsecValidateRule',
        request_serializer=control__pb2.MACsecValidateRule.SerializeToString,
        response_deserializer=control__pb2.control_status.FromString,
        )


class ControlServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def addMACsecProtectRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def addMACsecValidateRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteMACsecProtectRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteMACsecValidateRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'addMACsecProtectRule': grpc.unary_unary_rpc_method_handler(
          servicer.addMACsecProtectRule,
          request_deserializer=control__pb2.MACsecProtectRule.FromString,
          response_serializer=control__pb2.control_status.SerializeToString,
      ),
      'addMACsecValidateRule': grpc.unary_unary_rpc_method_handler(
          servicer.addMACsecValidateRule,
          request_deserializer=control__pb2.MACsecValidateRule.FromString,
          response_serializer=control__pb2.control_status.SerializeToString,
      ),
      'deleteMACsecProtectRule': grpc.unary_unary_rpc_method_handler(
          servicer.deleteMACsecProtectRule,
          request_deserializer=control__pb2.MACsecProtectRule.FromString,
          response_serializer=control__pb2.control_status.SerializeToString,
      ),
      'deleteMACsecValidateRule': grpc.unary_unary_rpc_method_handler(
          servicer.deleteMACsecValidateRule,
          request_deserializer=control__pb2.MACsecValidateRule.FromString,
          response_serializer=control__pb2.control_status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Control', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
