# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rcontrol.proto\"a\n\x11MACsecProtectRule\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0f\n\x07\x64st_mac\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\x0c\x12\x10\n\x08systemID\x18\x05 \x01(\t\"P\n\x12MACsecValidateRule\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0f\n\x07src_mac\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\x0c\"0\n\x0e\x63ontrol_status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x87\x02\n\x07\x43ontrol\x12;\n\x14\x61\x64\x64MACsecProtectRule\x12\x12.MACsecProtectRule\x1a\x0f.control_status\x12=\n\x15\x61\x64\x64MACsecValidateRule\x12\x13.MACsecValidateRule\x1a\x0f.control_status\x12>\n\x17\x64\x65leteMACsecProtectRule\x12\x12.MACsecProtectRule\x1a\x0f.control_status\x12@\n\x18\x64\x65leteMACsecValidateRule\x12\x13.MACsecValidateRule\x1a\x0f.control_statusb\x06proto3')
)




_MACSECPROTECTRULE = _descriptor.Descriptor(
  name='MACsecProtectRule',
  full_name='MACsecProtectRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='MACsecProtectRule.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='MACsecProtectRule.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_mac', full_name='MACsecProtectRule.dst_mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='MACsecProtectRule.key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='systemID', full_name='MACsecProtectRule.systemID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=114,
)


_MACSECVALIDATERULE = _descriptor.Descriptor(
  name='MACsecValidateRule',
  full_name='MACsecValidateRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='MACsecValidateRule.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='MACsecValidateRule.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_mac', full_name='MACsecValidateRule.src_mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='MACsecValidateRule.key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=196,
)


_CONTROL_STATUS = _descriptor.Descriptor(
  name='control_status',
  full_name='control_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='control_status.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='control_status.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['MACsecProtectRule'] = _MACSECPROTECTRULE
DESCRIPTOR.message_types_by_name['MACsecValidateRule'] = _MACSECVALIDATERULE
DESCRIPTOR.message_types_by_name['control_status'] = _CONTROL_STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MACsecProtectRule = _reflection.GeneratedProtocolMessageType('MACsecProtectRule', (_message.Message,), dict(
  DESCRIPTOR = _MACSECPROTECTRULE,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:MACsecProtectRule)
  ))
_sym_db.RegisterMessage(MACsecProtectRule)

MACsecValidateRule = _reflection.GeneratedProtocolMessageType('MACsecValidateRule', (_message.Message,), dict(
  DESCRIPTOR = _MACSECVALIDATERULE,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:MACsecValidateRule)
  ))
_sym_db.RegisterMessage(MACsecValidateRule)

control_status = _reflection.GeneratedProtocolMessageType('control_status', (_message.Message,), dict(
  DESCRIPTOR = _CONTROL_STATUS,
  __module__ = 'control_pb2'
  # @@protoc_insertion_point(class_scope:control_status)
  ))
_sym_db.RegisterMessage(control_status)



_CONTROL = _descriptor.ServiceDescriptor(
  name='Control',
  full_name='Control',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=249,
  serialized_end=512,
  methods=[
  _descriptor.MethodDescriptor(
    name='addMACsecProtectRule',
    full_name='Control.addMACsecProtectRule',
    index=0,
    containing_service=None,
    input_type=_MACSECPROTECTRULE,
    output_type=_CONTROL_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addMACsecValidateRule',
    full_name='Control.addMACsecValidateRule',
    index=1,
    containing_service=None,
    input_type=_MACSECVALIDATERULE,
    output_type=_CONTROL_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteMACsecProtectRule',
    full_name='Control.deleteMACsecProtectRule',
    index=2,
    containing_service=None,
    input_type=_MACSECPROTECTRULE,
    output_type=_CONTROL_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteMACsecValidateRule',
    full_name='Control.deleteMACsecValidateRule',
    index=3,
    containing_service=None,
    input_type=_MACSECVALIDATERULE,
    output_type=_CONTROL_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROL)

DESCRIPTOR.services_by_name['Control'] = _CONTROL

# @@protoc_insertion_point(module_scope)
